spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/swingy.db;OLD_INFORMATION_SCHEMA=TRUE
    name: ""
    password: ""
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

swingy:
  random:
    spread: 0.5
  battle:
    simulation:
      times: 100
  window:
    width: 1366
    height: 768