spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:file:./db/swingy.db;DATABASE_TO_UPPER=false
    name: sa
    password: ""
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create

swingy:
  random:
    spread: 0.2
  window:
    width: 800
    height: 600