spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/swingy.db;OLD_INFORMATION_SCHEMA=TRUE
    name: ""
    password: ""
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

swingy:
  random:
    spread: 0.2
  window:
    width: 800
    height: 600